<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>GBaseLite.CustomActions</AssemblyName>
    <RootNamespace>GBaseLite.CustomActions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WixToolset.Dtf.CustomAction" Version="5.0.2" />
    <Reference Include="System.ServiceProcess" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="CustomAction.config" />
    <Content Include="CustomAction.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
